// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://katdnpqytskvsrweqtjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdGRucHF5dHNrdnNyd2VxdGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDk1ODgsImV4cCI6MjA2NDcyNTU4OH0.sb7MGMlJeKfw4YIk1626SsyaMO73GkufEnohBJq5lcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);